### ISSUE TITLE
PerformanceCounter

### ISSUE THREAD

**Issue by ItsTeo04** [Glitcher85/WindowsDiscordRPC#1]
PerformanceCounter is not returning anything
example CPU XX%

**Comment by Glitcher85** [comment]
>  PerformanceCounter is not returning anything
> example CPU XX%

Hey there, ItsTeo04! May I ask, have you started the RPC? Since it usually shows XX on the GUI when it still hasn't started. Also, where is the XX showing up? On the GUI or the Discord Presence? I believe this may be an issue due to an outdated RPC ID. I'll be looking in the code once again soon enough.

**Comment by ItsTeo04** [comment]
Its started for 5mins and gui still shows XX%
I also tried WindowsRPC on second pc that has fresh installed windows
but windows wanst the problem 
btw sorry for bad english

**Comment by Glitcher85** [comment]
> Its started for 5mins and gui still shows XX%
> I also tried WindowsRPC on second pc that has fresh installed windows
> but windows wanst the problem 
> btw sorry for bad english

It seems you have misunderstood me. I never said Windows was a problem. It's an RPC ID issue. In any case, don't worry; I'll be looking into the issue soon, and post an update for the fix when I've the time.

**Comment by Glitcher85** [comment]
Hello, @ItsTeo04! I have fixed said problem and have uploaded v.0.2 out. May I ask you to try it out and inform me if it works?

**Comment by ItsTeo04** [comment]
Yeah it works
thanks for the update man
